Scoring:

Opponents

|Opponent | you | desc | score|
|---------|-----|------|------|
|A | X | Rock | 1|
| B | Y | Paper | 2 |
| C | Z | Siccors | 3 |

In [87]:
import numpy as np


with open("input2") as f:
    data = f.read().splitlines()
    
    
turns = np.array([turn.split(' ') for turn in data])
opp_turns = np.array(list(map(ord, turns[:, 0])))-64  # shift w/ 64 to get to 1, 2, 3

# toggle for ex1
my_turns = np.array(list(map(ord, turns[:, 1]))) - 87 # shift w/ 87 to get to 1, 2, 3

# toggle for ex2
outcomes = np.array(list(map(ord, turns[:, 1])))-89 # shift w/ 89 to get to -1, 0, 1
my_turns = opp_turns + outcomes
my_turns[my_turns==4] = 1
my_turns[my_turns==0] = 3

# difference
differences = opp_turns - my_turns
scoring = {
    -2: 0, # R v S
    -1: 6, # R v P or P v S
    0: 3,  # draw
    1: 0,  # P v R or S v P
    2: 6   # S v R
}
wins = np.array([scoring[difference] for difference in differences])

score = wins.sum() + my_turns.sum()
score

10116

In [92]:
my_turns[0:10], opp_turns[:10], outcomes[:10]

(array([3, 2, 1, 3, 2, 2, 3, 1, 1, 2]),
 array([3, 1, 2, 3, 2, 3, 3, 2, 2, 1]),
 array([ 0,  1, -1,  0,  0, -1,  0, -1, -1,  1]))